// Code generated by "stringer -type=Choice"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Rock-0]
	_ = x[Paper-1]
	_ = x[Scissors-2]
}

const _Choice_name = "RockPaperScissors"

var _Choice_index = [...]uint8{0, 4, 9, 17}

func (i Choice) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Choice_index)-1 {
		return "Choice(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Choice_name[_Choice_index[idx]:_Choice_index[idx+1]]
}
